const apartmentData = {
  a100: {
    status: 'free',
    size: '67',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: 'Földszint',
  },
  a101: {
    status: 'free',
    size: '62',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: 'Földszint',
  },
  a102: {
    status: 'free',
    size: '54',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: '1. emelet'
  },
  a103: {
    status: 'sold',
    size: '75',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: '1. emelet'
  },
  a201: {
    status: 'inprogress',
    size: '35',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: '2.emelet'
  },
  b100: {
    status: 'free',
    size: '43',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: 'Földszint'
  },
  b101: {
    status: 'inprogress',
    size: '55',
    rooms: '3',
    bathrooms: '2',
    balcony: '10',
    kitchen: 'amerikai konyha',
    floor: 'földszint, kerti ki- és bejárattal',
    appliances: 'mennyezet hűtés',
    floorNumber: '1-2. emelet',
  },
};

export default apartmentData;
